// Dummy data for ElectraFlow AI demo

export const ROLES = [
  "Admin",
  "Project Manager",
  "Senior Electrical Engineer",
  "Electrical Engineer",
  "QA/QC Engineer",
  "HR",
  "Executive",
  "Client",
] as const;
export type Role = (typeof ROLES)[number];

export const DISCIPLINES = [
  "Division 21 - Fire Suppression",
  "Division 22 - Plumbing",
  "Division 23 - HVAC",
  "Division 26 - Electrical",
  "Division 27 - Communications",
  "Division 28 - Security",
];

export const ACTION_CODES = ["REV,RNR", "NC,RNR", "NC,RES", "REJ,RES", "FOR RECORD ONLY"];

export const projects = [
  {
    id: "p1",
    number: "MEP-2025-001",
    name: "Riyadh Metro Phase 3 - Substation",
    client: "Royal Commission",
    location: "Riyadh, KSA",
    pm: "Ahmed Hassan",
    discipline: "Electrical",
    start: "2024-08-15",
    due: "2026-03-30",
    progress: 62,
    status: "On Track",
    budget: 4_250_000,
    actualCost: 2_310_000,
    contract: 5_100_000,
    risk: "Medium",
    priority: "High",
    contractor: "ALEC Engineering",
    consultant: "Parsons",
    engineers: ["Sara Khan", "Omar Faisal", "John Doe"],
    next: "2025-07-12",
  },
  {
    id: "p2",
    number: "MEP-2025-002",
    name: "NEOM Hotel Complex - MEP",
    client: "NEOM Co.",
    location: "Tabuk, KSA",
    pm: "Linda Park",
    discipline: "MEP",
    start: "2025-01-10",
    due: "2026-12-15",
    progress: 28,
    status: "On Track",
    budget: 9_800_000,
    actualCost: 2_140_000,
    contract: 11_200_000,
    risk: "Low",
    priority: "High",
    contractor: "Saudi Binladin",
    consultant: "AECOM",
    engineers: ["Maria Lopez", "Hassan Ali"],
    next: "2025-07-05",
  },
  {
    id: "p3",
    number: "MEP-2024-018",
    name: "Dubai Mall Expansion - HVAC",
    client: "Emaar",
    location: "Dubai, UAE",
    pm: "Rajiv Menon",
    discipline: "HVAC",
    start: "2024-03-01",
    due: "2025-08-20",
    progress: 84,
    status: "Delayed",
    budget: 3_400_000,
    actualCost: 3_120_000,
    contract: 3_900_000,
    risk: "High",
    priority: "Critical",
    contractor: "Al Naboodah",
    consultant: "Atkins",
    engineers: ["Priya Shah", "Mohammed Iqbal"],
    next: "2025-06-28",
  },
  {
    id: "p4",
    number: "MEP-2024-022",
    name: "King Salman Park - Fire Suppression",
    client: "Diriyah Gate",
    location: "Riyadh, KSA",
    pm: "Ahmed Hassan",
    discipline: "Fire",
    start: "2024-06-15",
    due: "2025-10-10",
    progress: 71,
    status: "On Track",
    budget: 1_850_000,
    actualCost: 1_220_000,
    contract: 2_100_000,
    risk: "Low",
    priority: "Medium",
    contractor: "Nesma",
    consultant: "WSP",
    engineers: ["Khalid Otaibi"],
    next: "2025-07-20",
  },
  {
    id: "p5",
    number: "MEP-2025-007",
    name: "Aramco HQ Renovation - Power",
    client: "Saudi Aramco",
    location: "Dhahran, KSA",
    pm: "Linda Park",
    discipline: "Electrical",
    start: "2025-02-01",
    due: "2026-06-30",
    progress: 18,
    status: "On Track",
    budget: 6_700_000,
    actualCost: 940_000,
    contract: 7_800_000,
    risk: "Medium",
    priority: "High",
    contractor: "Saudi Services",
    consultant: "Hill International",
    engineers: ["John Doe", "Sara Khan"],
    next: "2025-07-15",
  },
  {
    id: "p6",
    number: "MEP-2024-031",
    name: "Jeddah Airport T2 - Communications",
    client: "GACA",
    location: "Jeddah, KSA",
    pm: "Rajiv Menon",
    discipline: "Comms",
    start: "2024-09-05",
    due: "2025-09-01",
    progress: 92,
    status: "On Track",
    budget: 2_900_000,
    actualCost: 2_750_000,
    contract: 3_300_000,
    risk: "Low",
    priority: "Medium",
    contractor: "Almabani",
    consultant: "Dar Al-Handasah",
    engineers: ["Maria Lopez"],
    next: "2025-06-30",
  },
  {
    id: "p7",
    number: "MEP-2023-045",
    name: "Qiddiya Theme Park - Security",
    client: "Qiddiya Inv.",
    location: "Riyadh, KSA",
    pm: "Ahmed Hassan",
    discipline: "Security",
    start: "2023-11-01",
    due: "2025-05-30",
    progress: 96,
    status: "Delayed",
    budget: 4_100_000,
    actualCost: 4_050_000,
    contract: 4_500_000,
    risk: "High",
    priority: "High",
    contractor: "El Seif",
    consultant: "Mace",
    engineers: ["Omar Faisal", "Khalid Otaibi"],
    next: "2025-06-25",
  },
  {
    id: "p8",
    number: "MEP-2025-012",
    name: "Red Sea Resort - Plumbing",
    client: "Red Sea Global",
    location: "Tabuk, KSA",
    pm: "Linda Park",
    discipline: "Plumbing",
    start: "2025-04-10",
    due: "2026-08-15",
    progress: 8,
    status: "On Track",
    budget: 2_300_000,
    actualCost: 180_000,
    contract: 2_700_000,
    risk: "Low",
    priority: "Medium",
    contractor: "Drake & Scull",
    consultant: "Buro Happold",
    engineers: ["Hassan Ali"],
    next: "2025-07-22",
  },
];

export const submittals = [
  {
    id: "s1",
    section: "26 05 19",
    paragraph: "2.1.A",
    mark: "LV-CBL-01",
    product: "XLPE Power Cable 4C×95mm²",
    notes: "Brand matches spec; ratings OK.",
    status: "No Exception",
    action: "REV,RNR",
    assignedTo: "Sara Khan",
    due: "2025-07-08",
  },
  {
    id: "s2",
    section: "26 24 16",
    paragraph: "2.3.B",
    mark: "PNL-DB-04",
    product: "Distribution Panel 400A",
    notes: "Short-circuit rating below spec.",
    status: "Need Corrections",
    action: "NC,RNR",
    assignedTo: "Omar Faisal",
    due: "2025-07-05",
  },
  {
    id: "s3",
    section: "23 81 26",
    paragraph: "2.2.A",
    mark: "AHU-12",
    product: "Air Handling Unit 20,000 CFM",
    notes: "Different motor model proposed.",
    status: "Resubmittal Required",
    action: "NC,RES",
    assignedTo: "Priya Shah",
    due: "2025-07-10",
  },
  {
    id: "s4",
    section: "21 13 13",
    paragraph: "2.1.C",
    mark: "SPR-HD-02",
    product: "Quick Response Sprinkler",
    notes: "Wrong K-factor.",
    status: "Rejected",
    action: "REJ,RES",
    assignedTo: "Khalid Otaibi",
    due: "2025-07-03",
  },
  {
    id: "s5",
    section: "27 15 00",
    paragraph: "2.4.D",
    mark: "CAT6A-01",
    product: "Cat6A UTP Cable",
    notes: "Manufacturer datasheet only.",
    status: "For Record Only",
    action: "FOR RECORD ONLY",
    assignedTo: "Maria Lopez",
    due: "2025-07-12",
  },
  {
    id: "s6",
    section: "28 13 00",
    paragraph: "2.2.E",
    mark: "ACS-RDR-08",
    product: "HID Multi-class Reader",
    notes: "OSDP v2 confirmed.",
    status: "No Exception",
    action: "REV,RNR",
    assignedTo: "John Doe",
    due: "2025-07-09",
  },
  {
    id: "s7",
    section: "26 05 26",
    paragraph: "2.5.A",
    mark: "GND-BAR-01",
    product: "Copper Grounding Bar",
    notes: "Dimensions slightly off.",
    status: "Need Corrections",
    action: "NC,RNR",
    assignedTo: "Sara Khan",
    due: "2025-07-11",
  },
  {
    id: "s8",
    section: "22 11 16",
    paragraph: "2.1.B",
    mark: "DCW-PIPE",
    product: "Type L Copper Pipe",
    notes: "Compliant.",
    status: "No Exception",
    action: "REV,RNR",
    assignedTo: "Hassan Ali",
    due: "2025-07-14",
  },
];

export const employees = [
  {
    id: "e1",
    name: "Sara Khan",
    role: "Senior Electrical Engineer",
    current: "Riyadh Metro",
    next: "Aramco HQ",
    available: 8,
    assigned: 38,
    util: 95,
    status: "Overallocated",
    skills: {
      AutoCAD: 5,
      Revit: 4,
      ETAP: 5,
      SKM: 4,
      Bluebeam: 5,
      "Power BI": 3,
      Python: 2,
      "AI Tools": 3,
    },
  },
  {
    id: "e2",
    name: "Omar Faisal",
    role: "Electrical Engineer",
    current: "Riyadh Metro",
    next: "Qiddiya",
    available: 12,
    assigned: 32,
    util: 80,
    status: "Healthy",
    skills: {
      AutoCAD: 5,
      Revit: 3,
      ETAP: 4,
      SKM: 3,
      Bluebeam: 4,
      "Power BI": 2,
      Python: 1,
      "AI Tools": 2,
    },
  },
  {
    id: "e3",
    name: "John Doe",
    role: "Senior Engineer",
    current: "Aramco HQ",
    next: "Riyadh Metro",
    available: 6,
    assigned: 40,
    util: 100,
    status: "Overallocated",
    skills: {
      AutoCAD: 5,
      Revit: 5,
      ETAP: 5,
      SKM: 5,
      Bluebeam: 5,
      "Power BI": 4,
      Python: 3,
      "AI Tools": 4,
    },
  },
  {
    id: "e4",
    name: "Priya Shah",
    role: "HVAC Engineer",
    current: "Dubai Mall",
    next: "—",
    available: 20,
    assigned: 24,
    util: 60,
    status: "Available",
    skills: {
      AutoCAD: 4,
      Revit: 5,
      ETAP: 1,
      SKM: 1,
      Bluebeam: 4,
      "Power BI": 3,
      Python: 2,
      "AI Tools": 3,
    },
  },
  {
    id: "e5",
    name: "Maria Lopez",
    role: "Comms Engineer",
    current: "Jeddah Airport",
    next: "NEOM Hotel",
    available: 14,
    assigned: 30,
    util: 75,
    status: "Healthy",
    skills: {
      AutoCAD: 4,
      Revit: 3,
      ETAP: 1,
      SKM: 1,
      Bluebeam: 5,
      "Power BI": 4,
      Python: 4,
      "AI Tools": 4,
    },
  },
  {
    id: "e6",
    name: "Khalid Otaibi",
    role: "Fire Engineer",
    current: "King Salman Park",
    next: "Qiddiya",
    available: 10,
    assigned: 34,
    util: 85,
    status: "Healthy",
    skills: {
      AutoCAD: 5,
      Revit: 4,
      ETAP: 2,
      SKM: 2,
      Bluebeam: 5,
      "Power BI": 2,
      Python: 1,
      "AI Tools": 2,
    },
  },
  {
    id: "e7",
    name: "Hassan Ali",
    role: "Plumbing Engineer",
    current: "Red Sea Resort",
    next: "NEOM Hotel",
    available: 22,
    assigned: 22,
    util: 55,
    status: "Available",
    skills: {
      AutoCAD: 4,
      Revit: 4,
      ETAP: 1,
      SKM: 1,
      Bluebeam: 4,
      "Power BI": 3,
      Python: 2,
      "AI Tools": 3,
    },
  },
  {
    id: "e8",
    name: "Mohammed Iqbal",
    role: "QA/QC Lead",
    current: "Dubai Mall",
    next: "Aramco HQ",
    available: 8,
    assigned: 36,
    util: 90,
    status: "Healthy",
    skills: {
      AutoCAD: 3,
      Revit: 3,
      ETAP: 3,
      SKM: 3,
      Bluebeam: 5,
      "Power BI": 4,
      Python: 2,
      "AI Tools": 3,
    },
  },
];

export const documents = [
  {
    id: "d1",
    name: "Electrical Spec - Section 26.pdf",
    project: "Riyadh Metro",
    discipline: "Electrical",
    version: "v3.2",
    uploader: "Sara Khan",
    date: "2025-06-18",
    status: "Approved",
    size: "4.8 MB",
    type: "PDF",
  },
  {
    id: "d2",
    name: "Single Line Diagram - SS01.dwg",
    project: "Riyadh Metro",
    discipline: "Electrical",
    version: "v2.0",
    uploader: "John Doe",
    date: "2025-06-15",
    status: "In Review",
    size: "12.4 MB",
    type: "DWG",
  },
  {
    id: "d3",
    name: "HVAC Submittal Package.zip",
    project: "Dubai Mall",
    discipline: "HVAC",
    version: "v1.0",
    uploader: "Priya Shah",
    date: "2025-06-20",
    status: "Pending",
    size: "84.1 MB",
    type: "ZIP",
  },
  {
    id: "d4",
    name: "Cable Schedule.xlsx",
    project: "Aramco HQ",
    discipline: "Electrical",
    version: "v1.4",
    uploader: "Omar Faisal",
    date: "2025-06-12",
    status: "Approved",
    size: "1.2 MB",
    type: "XLSX",
  },
  {
    id: "d5",
    name: "Fire Pump Cut-sheet.pdf",
    project: "King Salman Park",
    discipline: "Fire",
    version: "v1.1",
    uploader: "Khalid Otaibi",
    date: "2025-06-10",
    status: "Approved",
    size: "2.3 MB",
    type: "PDF",
  },
  {
    id: "d6",
    name: "Site Photos June.jpg",
    project: "NEOM Hotel",
    discipline: "General",
    version: "v1.0",
    uploader: "Linda Park",
    date: "2025-06-22",
    status: "Approved",
    size: "8.7 MB",
    type: "JPG",
  },
  {
    id: "d7",
    name: "BOQ Revision C.docx",
    project: "Red Sea Resort",
    discipline: "MEP",
    version: "v3.0",
    uploader: "Hassan Ali",
    date: "2025-06-19",
    status: "In Review",
    size: "780 KB",
    type: "DOCX",
  },
  {
    id: "d8",
    name: "Control Panel Layout.png",
    project: "Qiddiya",
    discipline: "Electrical",
    version: "v2.1",
    uploader: "Omar Faisal",
    date: "2025-06-17",
    status: "Approved",
    size: "3.6 MB",
    type: "PNG",
  },
];

export const rfis = [
  {
    id: "r1",
    number: "RFI-001",
    project: "Riyadh Metro",
    subject: "Cable tray routing clash with HVAC duct",
    assignedTo: "Atkins",
    due: "2025-07-05",
    status: "Open",
    priority: "High",
  },
  {
    id: "r2",
    number: "RFI-002",
    project: "Dubai Mall",
    subject: "AHU base anchor detail clarification",
    assignedTo: "Atkins",
    due: "2025-07-02",
    status: "Answered",
    priority: "Medium",
  },
  {
    id: "r3",
    number: "RFI-003",
    project: "Aramco HQ",
    subject: "Transformer vault ventilation rate",
    assignedTo: "Hill Intl.",
    due: "2025-07-10",
    status: "Open",
    priority: "High",
  },
  {
    id: "r4",
    number: "RFI-004",
    project: "NEOM Hotel",
    subject: "Lighting control protocol selection",
    assignedTo: "AECOM",
    due: "2025-07-12",
    status: "Open",
    priority: "Low",
  },
  {
    id: "r5",
    number: "RFI-005",
    project: "Jeddah Airport",
    subject: "Fiber backbone redundancy path",
    assignedTo: "Dar",
    due: "2025-06-28",
    status: "Closed",
    priority: "Medium",
  },
];

export const ncrs = [
  {
    id: "n1",
    number: "NCR-001",
    project: "Dubai Mall",
    type: "Installation",
    root: "Wrong cable size used in run R-12",
    action: "Replace with 4C×95mm² XLPE",
    assignedTo: "Al Naboodah",
    status: "Open",
    due: "2025-07-08",
  },
  {
    id: "n2",
    number: "NCR-002",
    project: "Qiddiya",
    type: "Documentation",
    root: "Missing material certificate",
    action: "Submit mill test certificate",
    assignedTo: "El Seif",
    status: "In Progress",
    due: "2025-07-04",
  },
  {
    id: "n3",
    number: "NCR-003",
    project: "Riyadh Metro",
    type: "QA/QC",
    root: "Earth resistance > 5Ω",
    action: "Add ground rods and retest",
    assignedTo: "ALEC",
    status: "Closed",
    due: "2025-06-20",
  },
  {
    id: "n4",
    number: "NCR-004",
    project: "King Salman Park",
    type: "Safety",
    root: "Sprinkler head spacing exceeds NFPA 13",
    action: "Reposition heads per redline",
    assignedTo: "Nesma",
    status: "Open",
    due: "2025-07-11",
  },
];

export const meetings = [
  {
    id: "m1",
    title: "Riyadh Metro - Weekly Coordination",
    date: "2025-06-24",
    attendees: 8,
    actions: 5,
  },
  { id: "m2", title: "NEOM Hotel - Kickoff", date: "2025-06-20", attendees: 14, actions: 12 },
  { id: "m3", title: "Dubai Mall - Recovery Plan", date: "2025-06-18", attendees: 6, actions: 9 },
];

// ---------- Charts ----------
export const revenueTrend = [
  { m: "Jan", revenue: 1.2, profit: 0.28 },
  { m: "Feb", revenue: 1.4, profit: 0.32 },
  { m: "Mar", revenue: 1.7, profit: 0.41 },
  { m: "Apr", revenue: 1.5, profit: 0.34 },
  { m: "May", revenue: 1.9, profit: 0.46 },
  { m: "Jun", revenue: 2.2, profit: 0.55 },
  { m: "Jul", revenue: 2.4, profit: 0.6 },
  { m: "Aug", revenue: 2.1, profit: 0.5 },
  { m: "Sep", revenue: 2.6, profit: 0.66 },
  { m: "Oct", revenue: 2.8, profit: 0.71 },
  { m: "Nov", revenue: 3.0, profit: 0.78 },
  { m: "Dec", revenue: 3.3, profit: 0.84 },
];

export const projectStatus = [
  { name: "On Track", value: 5, color: "var(--color-success)" },
  { name: "Delayed", value: 2, color: "var(--color-warning)" },
  { name: "At Risk", value: 1, color: "var(--color-destructive)" },
];

export const workloadByMonth = [
  { m: "Jul", required: 42, available: 38 },
  { m: "Aug", required: 45, available: 38 },
  { m: "Sep", required: 50, available: 40 },
  { m: "Oct", required: 48, available: 42 },
  { m: "Nov", required: 44, available: 44 },
  { m: "Dec", required: 41, available: 44 },
  { m: "Jan", required: 46, available: 46 },
  { m: "Feb", required: 52, available: 46 },
  { m: "Mar", required: 55, available: 48 },
  { m: "Apr", required: 50, available: 50 },
];

export const upcomingSubmissions = [
  { d: "Wk 27", count: 6 },
  { d: "Wk 28", count: 9 },
  { d: "Wk 29", count: 4 },
  { d: "Wk 30", count: 11 },
  { d: "Wk 31", count: 7 },
  { d: "Wk 32", count: 5 },
];

export const costBreakdown = [
  { name: "Labor", value: 48, color: "var(--color-chart-1)" },
  { name: "Software", value: 6, color: "var(--color-chart-2)" },
  { name: "Travel", value: 4, color: "var(--color-chart-3)" },
  { name: "Subcontractors", value: 32, color: "var(--color-chart-4)" },
  { name: "Overhead", value: 10, color: "var(--color-chart-5)" },
];

export const cashFlow = [
  { m: "Jan", inflow: 1.1, outflow: 0.9 },
  { m: "Feb", inflow: 1.3, outflow: 1.0 },
  { m: "Mar", inflow: 1.5, outflow: 1.2 },
  { m: "Apr", inflow: 1.4, outflow: 1.3 },
  { m: "May", inflow: 1.8, outflow: 1.3 },
  { m: "Jun", inflow: 2.0, outflow: 1.5 },
];

export const milestoneTimeline = [
  { name: "Design Freeze", date: "Jul 5", project: "Riyadh Metro" },
  { name: "30% Submittals", date: "Jul 12", project: "NEOM Hotel" },
  { name: "Commissioning", date: "Jul 18", project: "Jeddah Airport" },
  { name: "Final Handover", date: "Jul 25", project: "King Salman Park" },
];

export const stats = {
  totalProjects: 24,
  activeProjects: 8,
  delayedProjects: 2,
  pendingSubmittals: 17,
  upcomingDeadlines: 11,
  revenue: 28.4, // M USD
  profitMargin: 24.6,
  utilization: 81,
  riskLevel: "Medium",
  billed: 21.2,
  collected: 18.7,
  outstanding: 4.1,
  retention: 2.3,
  cash: 6.4,
};

export const formatMoney = (n: number) =>
  n >= 1_000_000 ? `$${(n / 1_000_000).toFixed(2)}M` : `$${(n / 1_000).toFixed(0)}K`;

export const statusColor: Record<string, string> = {
  "On Track": "bg-success/15 text-success border-success/30",
  Delayed: "bg-warning/15 text-warning border-warning/30",
  "At Risk": "bg-destructive/15 text-destructive border-destructive/30",
  Approved: "bg-success/15 text-success border-success/30",
  "In Review": "bg-info/15 text-info border-info/30",
  Pending: "bg-warning/15 text-warning border-warning/30",
  Open: "bg-info/15 text-info border-info/30",
  Answered: "bg-success/15 text-success border-success/30",
  Closed: "bg-muted text-muted-foreground border-border",
  "In Progress": "bg-info/15 text-info border-info/30",
  "No Exception": "bg-success/15 text-success border-success/30",
  "Need Corrections": "bg-warning/15 text-warning border-warning/30",
  "Resubmittal Required": "bg-warning/15 text-warning border-warning/30",
  Rejected: "bg-destructive/15 text-destructive border-destructive/30",
  "For Record Only": "bg-muted text-muted-foreground border-border",
  Available: "bg-success/15 text-success border-success/30",
  Healthy: "bg-info/15 text-info border-info/30",
  Overallocated: "bg-destructive/15 text-destructive border-destructive/30",
};

export const riskColor: Record<string, string> = {
  Low: "bg-success/15 text-success border-success/30",
  Medium: "bg-warning/15 text-warning border-warning/30",
  High: "bg-destructive/15 text-destructive border-destructive/30",
};

// ─── Phase 11: Timesheets & Leave dummy data ──────────────────────────────────

export const dummyHolidays = [
  {
    id: "h1",
    organization_id: "mock-org",
    name: "Eid Al-Adha",
    holiday_date: "2026-06-27",
    recurring: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    created_by: null,
    deleted_at: null,
  },
  {
    id: "h2",
    organization_id: "mock-org",
    name: "Saudi National Day",
    holiday_date: "2026-09-23",
    recurring: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    created_by: null,
    deleted_at: null,
  },
  {
    id: "h3",
    organization_id: "mock-org",
    name: "Founding Day",
    holiday_date: "2026-02-22",
    recurring: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    created_by: null,
    deleted_at: null,
  },
];

export const dummyTimesheets = [
  {
    id: "ts1",
    organization_id: "mock-org",
    employee_id: "e1",
    employee_name: "Sara Khan",
    employee_number: "EMP-001",
    week_start_date: "2026-06-15",
    week_end_date: "2026-06-21",
    status: "approved",
    total_hours: 42,
    regular_hours: 40,
    overtime_hours: 2,
    submitted_at: "2026-06-21T18:00:00Z",
    approved_by: null,
    approved_by_name: "Admin Demo",
    approved_at: "2026-06-22T09:00:00Z",
    rejected_by: null,
    rejected_by_name: null,
    rejected_at: null,
    rejection_reason: null,
    unlock_reason: null,
    revision_number: 1,
    created_at: "2026-06-15T08:00:00Z",
    updated_at: "2026-06-22T09:00:00Z",
    created_by: null,
    deleted_at: null,
  },
  {
    id: "ts2",
    organization_id: "mock-org",
    employee_id: "e2",
    employee_name: "Omar Faisal",
    employee_number: "EMP-002",
    week_start_date: "2026-06-15",
    week_end_date: "2026-06-21",
    status: "submitted",
    total_hours: 38,
    regular_hours: 38,
    overtime_hours: 0,
    submitted_at: "2026-06-21T17:30:00Z",
    approved_by: null,
    approved_by_name: null,
    approved_at: null,
    rejected_by: null,
    rejected_by_name: null,
    rejected_at: null,
    rejection_reason: null,
    unlock_reason: null,
    revision_number: 1,
    created_at: "2026-06-15T08:00:00Z",
    updated_at: "2026-06-21T17:30:00Z",
    created_by: null,
    deleted_at: null,
  },
  {
    id: "ts3",
    organization_id: "mock-org",
    employee_id: "e1",
    employee_name: "Sara Khan",
    employee_number: "EMP-001",
    week_start_date: "2026-06-22",
    week_end_date: "2026-06-28",
    status: "draft",
    total_hours: 16,
    regular_hours: 16,
    overtime_hours: 0,
    submitted_at: null,
    approved_by: null,
    approved_by_name: null,
    approved_at: null,
    rejected_by: null,
    rejected_by_name: null,
    rejected_at: null,
    rejection_reason: null,
    unlock_reason: null,
    revision_number: 1,
    created_at: "2026-06-22T08:00:00Z",
    updated_at: "2026-06-22T12:00:00Z",
    created_by: null,
    deleted_at: null,
  },
];

export const dummyTimesheetEntries = [
  {
    id: "te1",
    organization_id: "mock-org",
    timesheet_id: "ts1",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 2",
    entry_date: "2026-06-15",
    hours: 8,
    work_type: "regular",
    description: "Cable schedule review",
    billable: true,
    is_weekend: false,
    created_at: "2026-06-15T09:00:00Z",
    updated_at: "2026-06-15T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "te2",
    organization_id: "mock-org",
    timesheet_id: "ts1",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 2",
    entry_date: "2026-06-16",
    hours: 8,
    work_type: "regular",
    description: "Panel schedule drawings",
    billable: true,
    is_weekend: false,
    created_at: "2026-06-16T09:00:00Z",
    updated_at: "2026-06-16T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "te3",
    organization_id: "mock-org",
    timesheet_id: "ts1",
    project_id: "p2",
    project_name: "Aramco HQ",
    entry_date: "2026-06-17",
    hours: 8,
    work_type: "regular",
    description: "Load schedule coordination",
    billable: true,
    is_weekend: false,
    created_at: "2026-06-17T09:00:00Z",
    updated_at: "2026-06-17T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "te4",
    organization_id: "mock-org",
    timesheet_id: "ts1",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 2",
    entry_date: "2026-06-18",
    hours: 8,
    work_type: "regular",
    description: "RFI responses",
    billable: true,
    is_weekend: false,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "te5",
    organization_id: "mock-org",
    timesheet_id: "ts1",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 2",
    entry_date: "2026-06-19",
    hours: 10,
    work_type: "overtime",
    description: "Submittal deadline crunch",
    billable: true,
    is_weekend: false,
    created_at: "2026-06-19T09:00:00Z",
    updated_at: "2026-06-19T09:00:00Z",
    deleted_at: null,
  },
];

export const dummyLeaveRequests = [
  {
    id: "lr1",
    organization_id: "mock-org",
    employee_id: "e2",
    employee_name: "Omar Faisal",
    leave_type: "pto",
    start_date: "2026-07-07",
    end_date: "2026-07-11",
    total_days: 5,
    reason: "Family vacation",
    status: "pending",
    approved_by: null,
    approved_by_name: null,
    approved_at: null,
    rejected_by: null,
    rejected_by_name: null,
    rejected_at: null,
    rejection_reason: null,
    created_at: "2026-06-20T10:00:00Z",
    updated_at: "2026-06-20T10:00:00Z",
    created_by: null,
    deleted_at: null,
    conflicts: [],
  },
  {
    id: "lr2",
    organization_id: "mock-org",
    employee_id: "e1",
    employee_name: "Sara Khan",
    leave_type: "sick",
    start_date: "2026-06-24",
    end_date: "2026-06-24",
    total_days: 1,
    reason: "Medical appointment",
    status: "approved",
    approved_by: null,
    approved_by_name: "HR Demo",
    approved_at: "2026-06-23T08:00:00Z",
    rejected_by: null,
    rejected_by_name: null,
    rejected_at: null,
    rejection_reason: null,
    created_at: "2026-06-23T07:00:00Z",
    updated_at: "2026-06-23T08:00:00Z",
    created_by: null,
    deleted_at: null,
    conflicts: [],
  },
];

// ─── Phase 12: Financial mock data ───────────────────────────────────────────

export const dummyProjectBudgets = [
  {
    id: "pb1",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 3 - Substation",
    project_number: "MEP-2025-001",
    organization_id: "mock-org",
    total_budget: 4_250_000,
    approved_changes: 180_000,
    revised_budget: 4_430_000,
    contingency_percent: 10,
    contingency_amount: 443_000,
    actual_expenses: 1_120_000,
    labor_cost: 860_000,
    total_actual: 1_980_000,
    variance: 2_450_000,
    variance_percent: 55.3,
    billed: 2_100_000,
    collected: 1_800_000,
    outstanding: 300_000,
    notes: "Budget approved by steering committee Jan 2025.",
    created_by: null,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2026-06-01T10:00:00Z",
    deleted_at: null,
  },
  {
    id: "pb2",
    project_id: "p2",
    project_name: "NEOM Hotel Complex - MEP",
    project_number: "MEP-2025-002",
    organization_id: "mock-org",
    total_budget: 2_800_000,
    approved_changes: 0,
    revised_budget: 2_800_000,
    contingency_percent: 10,
    contingency_amount: 280_000,
    actual_expenses: 420_000,
    labor_cost: 310_000,
    total_actual: 730_000,
    variance: 2_070_000,
    variance_percent: 73.9,
    billed: 700_000,
    collected: 700_000,
    outstanding: 0,
    notes: null,
    created_by: null,
    created_at: "2025-01-20T09:00:00Z",
    updated_at: "2026-06-01T10:00:00Z",
    deleted_at: null,
  },
  {
    id: "pb3",
    project_id: "p3",
    project_name: "Aramco HQ Expansion",
    project_number: "MEP-2024-003",
    organization_id: "mock-org",
    total_budget: 1_600_000,
    approved_changes: -50_000,
    revised_budget: 1_550_000,
    contingency_percent: 8,
    contingency_amount: 124_000,
    actual_expenses: 980_000,
    labor_cost: 420_000,
    total_actual: 1_400_000,
    variance: 150_000,
    variance_percent: 9.7,
    billed: 1_400_000,
    collected: 1_250_000,
    outstanding: 150_000,
    notes: "Credit CO issued for scope reduction on Level 4.",
    created_by: null,
    created_at: "2024-06-01T09:00:00Z",
    updated_at: "2026-06-01T10:00:00Z",
    deleted_at: null,
  },
];

export const dummyExpenses = [
  {
    id: "ex1",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 3 - Substation",
    project_number: "MEP-2025-001",
    organization_id: "mock-org",
    category: "material",
    description: "High-voltage cable procurement — 33kV XLPE",
    amount: 320_000,
    expense_date: "2025-03-15",
    vendor: "Prysmian Group",
    reference_number: "PO-2025-0041",
    billable: true,
    status: "approved",
    approved_by: null,
    approved_by_name: "Ahmed Hassan",
    approved_at: "2025-03-18T10:00:00Z",
    rejection_reason: null,
    created_by: null,
    created_by_name: "Sara Khan",
    created_at: "2025-03-15T09:00:00Z",
    updated_at: "2025-03-18T10:00:00Z",
    deleted_at: null,
  },
  {
    id: "ex2",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 3 - Substation",
    project_number: "MEP-2025-001",
    organization_id: "mock-org",
    category: "subcontractor",
    description: "Cable installation subcontract — Phase 1 scope",
    amount: 480_000,
    expense_date: "2025-04-10",
    vendor: "ALEC Electrical",
    reference_number: "SC-2025-012",
    billable: true,
    status: "approved",
    approved_by: null,
    approved_by_name: "Ahmed Hassan",
    approved_at: "2025-04-12T10:00:00Z",
    rejection_reason: null,
    created_by: null,
    created_by_name: "Ahmed Hassan",
    created_at: "2025-04-10T09:00:00Z",
    updated_at: "2025-04-12T10:00:00Z",
    deleted_at: null,
  },
  {
    id: "ex3",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 3 - Substation",
    project_number: "MEP-2025-001",
    organization_id: "mock-org",
    category: "travel",
    description: "Site visits — Riyadh (3 trips)",
    amount: 8_500,
    expense_date: "2025-05-20",
    vendor: null,
    reference_number: null,
    billable: false,
    status: "approved",
    approved_by: null,
    approved_by_name: "Ahmed Hassan",
    approved_at: "2025-05-22T08:00:00Z",
    rejection_reason: null,
    created_by: null,
    created_by_name: "Omar Faisal",
    created_at: "2025-05-20T09:00:00Z",
    updated_at: "2025-05-22T08:00:00Z",
    deleted_at: null,
  },
  {
    id: "ex4",
    project_id: "p2",
    project_name: "NEOM Hotel Complex - MEP",
    project_number: "MEP-2025-002",
    organization_id: "mock-org",
    category: "equipment",
    description: "Temporary power distribution units — site setup",
    amount: 65_000,
    expense_date: "2025-02-28",
    vendor: "Aggreko",
    reference_number: "PO-2025-0018",
    billable: true,
    status: "approved",
    approved_by: null,
    approved_by_name: "Linda Park",
    approved_at: "2025-03-02T10:00:00Z",
    rejection_reason: null,
    created_by: null,
    created_by_name: "Linda Park",
    created_at: "2025-02-28T09:00:00Z",
    updated_at: "2025-03-02T10:00:00Z",
    deleted_at: null,
  },
  {
    id: "ex5",
    project_id: "p3",
    project_name: "Aramco HQ Expansion",
    project_number: "MEP-2024-003",
    organization_id: "mock-org",
    category: "material",
    description: "Switchgear panels — MV room Level B1",
    amount: 210_000,
    expense_date: "2024-09-05",
    vendor: "Schneider Electric",
    reference_number: "PO-2024-0067",
    billable: true,
    status: "approved",
    approved_by: null,
    approved_by_name: "Ahmed Hassan",
    approved_at: "2024-09-08T10:00:00Z",
    rejection_reason: null,
    created_by: null,
    created_by_name: "John Doe",
    created_at: "2024-09-05T09:00:00Z",
    updated_at: "2024-09-08T10:00:00Z",
    deleted_at: null,
  },
  {
    id: "ex6",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 3 - Substation",
    project_number: "MEP-2025-001",
    organization_id: "mock-org",
    category: "software",
    description: "AutoCAD Electrical license — 3 seats, 12 months",
    amount: 4_200,
    expense_date: "2026-01-01",
    vendor: "Autodesk",
    reference_number: "AUT-2026-SE",
    billable: false,
    status: "pending",
    approved_by: null,
    approved_by_name: null,
    approved_at: null,
    rejection_reason: null,
    created_by: null,
    created_by_name: "Sara Khan",
    created_at: "2026-01-01T09:00:00Z",
    updated_at: "2026-01-01T09:00:00Z",
    deleted_at: null,
  },
];

export const dummyChangeOrders = [
  {
    id: "co1",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 3 - Substation",
    project_number: "MEP-2025-001",
    organization_id: "mock-org",
    co_number: "CO-001",
    title: "Additional protection relay panels — Station 7",
    description:
      "Client requested 4 additional bay protection panels not in original scope. Covers supply, installation and commissioning.",
    amount: 180_000,
    status: "approved",
    submitted_by: null,
    submitted_by_name: "Ahmed Hassan",
    submitted_at: "2025-06-10T09:00:00Z",
    reviewed_by: null,
    reviewed_by_name: "Project Director",
    reviewed_at: "2025-06-15T14:00:00Z",
    rejection_reason: null,
    void_reason: null,
    revision_number: 1,
    created_by: null,
    created_by_name: "Ahmed Hassan",
    created_at: "2025-06-10T09:00:00Z",
    updated_at: "2025-06-15T14:00:00Z",
    deleted_at: null,
  },
  {
    id: "co2",
    project_id: "p3",
    project_name: "Aramco HQ Expansion",
    project_number: "MEP-2024-003",
    organization_id: "mock-org",
    co_number: "CO-001",
    title: "Credit: Scope reduction Level 4 electrical rooms",
    description:
      "Client reduced scope — Level 4 North wing electrical works deferred to Phase 2. Credit agreed with client.",
    amount: -50_000,
    status: "approved",
    submitted_by: null,
    submitted_by_name: "Linda Park",
    submitted_at: "2024-11-01T09:00:00Z",
    reviewed_by: null,
    reviewed_by_name: "Project Director",
    reviewed_at: "2024-11-05T14:00:00Z",
    rejection_reason: null,
    void_reason: null,
    revision_number: 1,
    created_by: null,
    created_by_name: "Linda Park",
    created_at: "2024-11-01T09:00:00Z",
    updated_at: "2024-11-05T14:00:00Z",
    deleted_at: null,
  },
  {
    id: "co3",
    project_id: "p2",
    project_name: "NEOM Hotel Complex - MEP",
    project_number: "MEP-2025-002",
    organization_id: "mock-org",
    co_number: "CO-001",
    title: "EV charging infrastructure — Car park B",
    description: "Addition of 24 EV charging points in Car Park B including dedicated MDB.",
    amount: 95_000,
    status: "submitted",
    submitted_by: null,
    submitted_by_name: "Linda Park",
    submitted_at: "2026-06-01T09:00:00Z",
    reviewed_by: null,
    reviewed_by_name: null,
    reviewed_at: null,
    rejection_reason: null,
    void_reason: null,
    revision_number: 1,
    created_by: null,
    created_by_name: "Linda Park",
    created_at: "2026-05-28T09:00:00Z",
    updated_at: "2026-06-01T09:00:00Z",
    deleted_at: null,
  },
];

export const dummyInvoices = [
  {
    id: "inv1",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 3 - Substation",
    project_number: "MEP-2025-001",
    organization_id: "mock-org",
    invoice_number: "INV-2025-001",
    title: "Milestone 1 — Design Complete",
    client_name: "Royal Commission",
    status: "paid",
    issue_date: "2025-04-01",
    due_date: "2025-04-30",
    subtotal: 900_000,
    tax_rate: 15,
    tax_amount: 135_000,
    total_amount: 1_035_000,
    paid_amount: 1_035_000,
    outstanding_amount: 0,
    notes: "Payment received 2025-04-28.",
    created_by: null,
    created_by_name: "Ahmed Hassan",
    created_at: "2025-04-01T09:00:00Z",
    updated_at: "2025-04-28T10:00:00Z",
    deleted_at: null,
    is_overdue: false,
    items: [
      {
        id: "ii1",
        invoice_id: "inv1",
        description: "Engineering design — 33kV substation schematic & SLD",
        quantity: 1,
        unit_price: 600_000,
        amount: 600_000,
        sort_order: 0,
      },
      {
        id: "ii2",
        invoice_id: "inv1",
        description: "Design review coordination (5 workshops)",
        quantity: 5,
        unit_price: 60_000,
        amount: 300_000,
        sort_order: 1,
      },
    ],
    payments: [
      {
        id: "pay1",
        invoice_id: "inv1",
        invoice_number: "INV-2025-001",
        project_id: "p1",
        project_name: "Riyadh Metro Phase 3 - Substation",
        organization_id: "mock-org",
        amount: 1_035_000,
        payment_date: "2025-04-28",
        method: "bank_transfer",
        reference_number: "TRF-RC-20250428",
        notes: null,
        created_by: null,
        created_by_name: "Ahmed Hassan",
        created_at: "2025-04-28T10:00:00Z",
      },
    ],
  },
  {
    id: "inv2",
    project_id: "p1",
    project_name: "Riyadh Metro Phase 3 - Substation",
    project_number: "MEP-2025-001",
    organization_id: "mock-org",
    invoice_number: "INV-2025-002",
    title: "Milestone 2 — Procurement & FAT",
    client_name: "Royal Commission",
    status: "sent",
    issue_date: "2026-03-01",
    due_date: "2026-03-31",
    subtotal: 1_000_000,
    tax_rate: 15,
    tax_amount: 150_000,
    total_amount: 1_150_000,
    paid_amount: 0,
    outstanding_amount: 1_150_000,
    notes: null,
    created_by: null,
    created_by_name: "Ahmed Hassan",
    created_at: "2026-03-01T09:00:00Z",
    updated_at: "2026-03-01T09:00:00Z",
    deleted_at: null,
    is_overdue: true,
    items: [
      {
        id: "ii3",
        invoice_id: "inv2",
        description: "Procurement management — switchgear & protection relays",
        quantity: 1,
        unit_price: 700_000,
        amount: 700_000,
        sort_order: 0,
      },
      {
        id: "ii4",
        invoice_id: "inv2",
        description: "Factory Acceptance Testing (FAT) — site attendance × 3",
        quantity: 3,
        unit_price: 100_000,
        amount: 300_000,
        sort_order: 1,
      },
    ],
    payments: [],
  },
  {
    id: "inv3",
    project_id: "p2",
    project_name: "NEOM Hotel Complex - MEP",
    project_number: "MEP-2025-002",
    organization_id: "mock-org",
    invoice_number: "INV-2025-003",
    title: "Monthly progress — January 2025",
    client_name: "NEOM Co.",
    status: "paid",
    issue_date: "2025-01-31",
    due_date: "2025-02-28",
    subtotal: 700_000,
    tax_rate: 15,
    tax_amount: 105_000,
    total_amount: 805_000,
    paid_amount: 805_000,
    outstanding_amount: 0,
    notes: null,
    created_by: null,
    created_by_name: "Linda Park",
    created_at: "2025-01-31T09:00:00Z",
    updated_at: "2025-02-20T10:00:00Z",
    deleted_at: null,
    is_overdue: false,
    items: [
      {
        id: "ii5",
        invoice_id: "inv3",
        description: "MEP design progress — January 2025 (28%)",
        quantity: 1,
        unit_price: 700_000,
        amount: 700_000,
        sort_order: 0,
      },
    ],
    payments: [
      {
        id: "pay2",
        invoice_id: "inv3",
        invoice_number: "INV-2025-003",
        project_id: "p2",
        project_name: "NEOM Hotel Complex - MEP",
        organization_id: "mock-org",
        amount: 805_000,
        payment_date: "2025-02-20",
        method: "bank_transfer",
        reference_number: "TRF-NEOM-20250220",
        notes: null,
        created_by: null,
        created_by_name: "Linda Park",
        created_at: "2025-02-20T10:00:00Z",
      },
    ],
  },
];

// ─── Phase 13: Mock Notifications ─────────────────────────────────────────────

import type { Notification, ActivityEvent, NotificationPreference } from "@/types/database";

const NOW = new Date();
const mins = (n: number) => new Date(NOW.getTime() - n * 60 * 1000).toISOString();
const hrs = (n: number) => new Date(NOW.getTime() - n * 60 * 60 * 1000).toISOString();
const days = (n: number) => new Date(NOW.getTime() - n * 24 * 60 * 60 * 1000).toISOString();

export const dummyNotifications: Notification[] = [
  {
    id: "notif-1",
    organization_id: "mock-org",
    recipient_profile_id: "mock-profile",
    actor_profile_id: "mock-actor-1",
    event_type: "submittal.approved",
    title: "Submittal approved",
    message: "MEP-SUB-001 — Panel Schedule Layout has been approved by Ahmed Hassan.",
    entity_type: "submittal",
    entity_id: "sub1",
    route: "/submittals/sub1",
    priority: "normal",
    category: "submittal",
    severity: "success",
    is_pinned: true,
    read_at: null,
    dismissed_at: null,
    snoozed_until: null,
    created_at: mins(15),
    deleted_at: null,
  },
  {
    id: "notif-2",
    organization_id: "mock-org",
    recipient_profile_id: "mock-profile",
    actor_profile_id: "mock-actor-2",
    event_type: "rfi.assigned",
    title: "RFI assigned to you",
    message: "RFI-003 — Conduit routing conflict has been assigned to you. Response due in 5 days.",
    entity_type: "rfi",
    entity_id: "rfi3",
    route: "/rfis/rfi3",
    priority: "high",
    category: "rfi",
    severity: "warning",
    is_pinned: false,
    read_at: null,
    dismissed_at: null,
    snoozed_until: null,
    created_at: hrs(1),
    deleted_at: null,
  },
  {
    id: "notif-3",
    organization_id: "mock-org",
    recipient_profile_id: "mock-profile",
    actor_profile_id: null,
    event_type: "certification.expiring",
    title: "Certification expiring soon",
    message:
      "Omar Faisal's Electrical Engineer license expires in 14 days. Please arrange renewal.",
    entity_type: "employee",
    entity_id: "e2",
    route: "/resources/e2",
    priority: "high",
    category: "resource",
    severity: "warning",
    is_pinned: false,
    read_at: null,
    dismissed_at: null,
    snoozed_until: null,
    created_at: hrs(3),
    deleted_at: null,
  },
  {
    id: "notif-4",
    organization_id: "mock-org",
    recipient_profile_id: "mock-profile",
    actor_profile_id: "mock-actor-3",
    event_type: "timesheet.submitted",
    title: "Timesheet submitted for review",
    message: "Sara Khan submitted a timesheet for week ending 2025-01-26 (40.0 hrs).",
    entity_type: "timesheet",
    entity_id: "ts1",
    route: "/timesheets",
    priority: "normal",
    category: "timesheet",
    severity: "info",
    is_pinned: false,
    read_at: hrs(2),
    dismissed_at: null,
    snoozed_until: null,
    created_at: hrs(5),
    deleted_at: null,
  },
  {
    id: "notif-5",
    organization_id: "mock-org",
    recipient_profile_id: "mock-profile",
    actor_profile_id: null,
    event_type: "invoice.overdue",
    title: "Invoice overdue",
    message: "INV-2025-001 for Riyadh Metro Extension (SAR 1,350,000) is 5 days overdue.",
    entity_type: "invoice",
    entity_id: "inv1",
    route: "/financials",
    priority: "critical",
    category: "financial",
    severity: "error",
    is_pinned: false,
    read_at: null,
    dismissed_at: null,
    snoozed_until: null,
    created_at: hrs(8),
    deleted_at: null,
  },
  {
    id: "notif-6",
    organization_id: "mock-org",
    recipient_profile_id: "mock-profile",
    actor_profile_id: "mock-actor-1",
    event_type: "ncr.created",
    title: "NCR opened on your project",
    message:
      "NCR-007 — Incorrect cable tray installation has been raised on Riyadh Metro Extension.",
    entity_type: "ncr",
    entity_id: "ncr7",
    route: "/ncrs",
    priority: "high",
    category: "ncr",
    severity: "error",
    is_pinned: false,
    read_at: null,
    dismissed_at: null,
    snoozed_until: null,
    created_at: days(1),
    deleted_at: null,
  },
  {
    id: "notif-7",
    organization_id: "mock-org",
    recipient_profile_id: "mock-profile",
    actor_profile_id: "mock-actor-4",
    event_type: "document.approved",
    title: "Document approved",
    message: "Panel Schedule Drawing Rev.3 has been approved and is ready for issue.",
    entity_type: "document",
    entity_id: "doc3",
    route: "/documents/doc3",
    priority: "normal",
    category: "document",
    severity: "success",
    is_pinned: false,
    read_at: days(1),
    dismissed_at: null,
    snoozed_until: null,
    created_at: days(2),
    deleted_at: null,
  },
  {
    id: "notif-8",
    organization_id: "mock-org",
    recipient_profile_id: "mock-profile",
    actor_profile_id: "mock-actor-1",
    event_type: "expense.approved",
    title: "Expense approved",
    message: "Material purchase (SAR 45,000) for cable trays has been approved.",
    entity_type: "expense",
    entity_id: "exp1",
    route: "/financials",
    priority: "low",
    category: "financial",
    severity: "success",
    is_pinned: false,
    read_at: days(2),
    dismissed_at: null,
    snoozed_until: null,
    created_at: days(3),
    deleted_at: null,
  },
];

export const dummyActivityEvents: ActivityEvent[] = [
  {
    id: "ae-1",
    organization_id: "mock-org",
    actor_profile_id: "mock-actor-1",
    event_type: "project.status_changed",
    entity_type: "project",
    entity_id: "p1",
    entity_label: "Riyadh Metro Extension",
    message: "Ahmed Hassan changed the status of Riyadh Metro Extension to Active.",
    metadata: { old_status: "planning", new_status: "active" },
    category: "project",
    visibility: "internal",
    created_at: mins(30),
    deleted_at: null,
  },
  {
    id: "ae-2",
    organization_id: "mock-org",
    actor_profile_id: "mock-actor-3",
    event_type: "timesheet.submitted",
    entity_type: "timesheet",
    entity_id: "ts1",
    entity_label: "Week ending 2025-01-26",
    message: "Sara Khan submitted a timesheet for 40.0 hours.",
    metadata: { hours: 40, week_ending: "2025-01-26" },
    category: "timesheet",
    visibility: "internal",
    created_at: hrs(1),
    deleted_at: null,
  },
  {
    id: "ae-3",
    organization_id: "mock-org",
    actor_profile_id: "mock-actor-1",
    event_type: "submittal.approved",
    entity_type: "submittal",
    entity_id: "sub1",
    entity_label: "MEP-SUB-001",
    message: "Ahmed Hassan approved submittal MEP-SUB-001 — Panel Schedule Layout.",
    metadata: { submittal_number: "MEP-SUB-001" },
    category: "submittal",
    visibility: "internal",
    created_at: hrs(2),
    deleted_at: null,
  },
  {
    id: "ae-4",
    organization_id: "mock-org",
    actor_profile_id: null,
    event_type: "invoice.overdue",
    entity_type: "invoice",
    entity_id: "inv1",
    entity_label: "INV-2025-001",
    message: "Invoice INV-2025-001 (SAR 1,350,000) is now overdue.",
    metadata: { amount: 1350000, days_overdue: 5 },
    category: "financial",
    visibility: "internal",
    created_at: hrs(8),
    deleted_at: null,
  },
  {
    id: "ae-5",
    organization_id: "mock-org",
    actor_profile_id: "mock-actor-4",
    event_type: "document.approved",
    entity_type: "document",
    entity_id: "doc3",
    entity_label: "Panel Schedule Drawing Rev.3",
    message: "Linda Park approved Panel Schedule Drawing Rev.3.",
    metadata: { document_title: "Panel Schedule Drawing", revision: 3 },
    category: "document",
    visibility: "client_visible",
    created_at: days(1),
    deleted_at: null,
  },
  {
    id: "ae-6",
    organization_id: "mock-org",
    actor_profile_id: "mock-actor-2",
    event_type: "rfi.assigned",
    entity_type: "rfi",
    entity_id: "rfi3",
    entity_label: "RFI-003",
    message: "Omar Faisal assigned RFI-003 — Conduit routing conflict.",
    metadata: { rfi_number: "RFI-003" },
    category: "rfi",
    visibility: "internal",
    created_at: hrs(1),
    deleted_at: null,
  },
  {
    id: "ae-7",
    organization_id: "mock-org",
    actor_profile_id: "mock-actor-1",
    event_type: "expense.approved",
    entity_type: "expense",
    entity_id: "exp1",
    entity_label: "Material purchase — Cable trays",
    message: "Ahmed Hassan approved expense for SAR 45,000 (Material purchase — Cable trays).",
    metadata: { amount: 45000, category: "material" },
    category: "financial",
    visibility: "internal",
    created_at: days(3),
    deleted_at: null,
  },
  {
    id: "ae-8",
    organization_id: "mock-org",
    actor_profile_id: "mock-actor-1",
    event_type: "change_order.approved",
    entity_type: "change_order",
    entity_id: "co1",
    entity_label: "CO-001",
    message: "Ahmed Hassan approved Change Order CO-001 for SAR 250,000.",
    metadata: { amount: 250000, co_number: "CO-001" },
    category: "financial",
    visibility: "client_visible",
    created_at: days(5),
    deleted_at: null,
  },
];

export const dummyNotificationPreferences: NotificationPreference[] = [
  {
    id: "pref-1",
    organization_id: "mock-org",
    profile_id: "mock-profile",
    channel: "in_app",
    event_type: "submittal.approved",
    enabled: true,
    frequency: "immediate",
    created_at: days(30),
    updated_at: days(30),
  },
  {
    id: "pref-2",
    organization_id: "mock-org",
    profile_id: "mock-profile",
    channel: "in_app",
    event_type: "rfi.assigned",
    enabled: true,
    frequency: "immediate",
    created_at: days(30),
    updated_at: days(30),
  },
  {
    id: "pref-3",
    organization_id: "mock-org",
    profile_id: "mock-profile",
    channel: "in_app",
    event_type: "timesheet.submitted",
    enabled: false,
    frequency: "daily_digest",
    created_at: days(30),
    updated_at: days(15),
  },
];
