/**
 * AI backend status banner — Phase 15C
 */

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { AlertTriangle, Sparkles, RefreshCw } from "lucide-react";
import { isAIConfigured } from "@/lib/ai-provider";

interface AIBackendBannerProps {
  onRetry?: () => void;
  className?: string;
}

export function AIBackendBanner({ onRetry, className }: AIBackendBannerProps) {
  const configured = isAIConfigured();

  if (configured) {
    return (
      <Alert className={className}>
        <Sparkles className="h-4 w-4" />
        <AlertTitle>AI backend connected</AlertTitle>
        <AlertDescription>Responses are generated by the configured provider.</AlertDescription>
      </Alert>
    );
  }

  return (
    <Alert variant="default" className={`border-amber-500/50 bg-amber-500/5 ${className ?? ""}`}>
      <AlertTriangle className="h-4 w-4 text-amber-600" />
      <AlertTitle>AI backend not configured</AlertTitle>
      <AlertDescription className="flex flex-col sm:flex-row sm:items-center gap-2">
        <span>
          Chat history and suggestions work, but answers will not be generated until a server-side
          AI provider is configured. No fabricated responses are shown.
        </span>
        {onRetry && (
          <Button variant="outline" size="sm" onClick={onRetry} className="shrink-0">
            <RefreshCw className="h-3.5 w-3.5 mr-1" />
            Retry
          </Button>
        )}
      </AlertDescription>
    </Alert>
  );
}
