/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppWorkloadRouteImport } from './routes/_app.workload'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSubmittalsRouteImport } from './routes/_app.submittals'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRfiRouteImport } from './routes/_app.rfi'
import { Route as AppResourcesRouteImport } from './routes/_app.resources'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppPmRouteImport } from './routes/_app.pm'
import { Route as AppNcrRouteImport } from './routes/_app.ncr'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppFinancialsRouteImport } from './routes/_app.financials'
import { Route as AppExecutiveRouteImport } from './routes/_app.executive'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppClientPortalRouteImport } from './routes/_app.client-portal'
import { Route as AppAppsRouteImport } from './routes/_app.apps'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppSubmittalsIdRouteImport } from './routes/_app.submittals.$id'
import { Route as AppRfiIdRouteImport } from './routes/_app.rfi.$id'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppDocumentsIdRouteImport } from './routes/_app.documents.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkloadRoute = AppWorkloadRouteImport.update({
  id: '/workload',
  path: '/workload',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmittalsRoute = AppSubmittalsRouteImport.update({
  id: '/submittals',
  path: '/submittals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRfiRoute = AppRfiRouteImport.update({
  id: '/rfi',
  path: '/rfi',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPmRoute = AppPmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => AppRoute,
} as any)
const AppNcrRoute = AppNcrRouteImport.update({
  id: '/ncr',
  path: '/ncr',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialsRoute = AppFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutiveRoute = AppExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppClientPortalRoute = AppClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsRoute = AppAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmittalsIdRoute = AppSubmittalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSubmittalsRoute,
} as any)
const AppRfiIdRoute = AppRfiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRfiRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppDocumentsIdRoute = AppDocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/ai': typeof AppAiRoute
  '/apps': typeof AppAppsRoute
  '/client-portal': typeof AppClientPortalRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/executive': typeof AppExecutiveRoute
  '/financials': typeof AppFinancialsRoute
  '/hr': typeof AppHrRoute
  '/meetings': typeof AppMeetingsRoute
  '/ncr': typeof AppNcrRoute
  '/pm': typeof AppPmRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/resources': typeof AppResourcesRoute
  '/rfi': typeof AppRfiRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/submittals': typeof AppSubmittalsRouteWithChildren
  '/users': typeof AppUsersRoute
  '/workload': typeof AppWorkloadRoute
  '/invite/$token': typeof InviteTokenRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/rfi/$id': typeof AppRfiIdRoute
  '/submittals/$id': typeof AppSubmittalsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/ai': typeof AppAiRoute
  '/apps': typeof AppAppsRoute
  '/client-portal': typeof AppClientPortalRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/executive': typeof AppExecutiveRoute
  '/financials': typeof AppFinancialsRoute
  '/hr': typeof AppHrRoute
  '/meetings': typeof AppMeetingsRoute
  '/ncr': typeof AppNcrRoute
  '/pm': typeof AppPmRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/resources': typeof AppResourcesRoute
  '/rfi': typeof AppRfiRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/submittals': typeof AppSubmittalsRouteWithChildren
  '/users': typeof AppUsersRoute
  '/workload': typeof AppWorkloadRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AppIndexRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/rfi/$id': typeof AppRfiIdRoute
  '/submittals/$id': typeof AppSubmittalsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/apps': typeof AppAppsRoute
  '/_app/client-portal': typeof AppClientPortalRoute
  '/_app/documents': typeof AppDocumentsRouteWithChildren
  '/_app/executive': typeof AppExecutiveRoute
  '/_app/financials': typeof AppFinancialsRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/ncr': typeof AppNcrRoute
  '/_app/pm': typeof AppPmRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/rfi': typeof AppRfiRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/submittals': typeof AppSubmittalsRouteWithChildren
  '/_app/users': typeof AppUsersRoute
  '/_app/workload': typeof AppWorkloadRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/documents/$id': typeof AppDocumentsIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/rfi/$id': typeof AppRfiIdRoute
  '/_app/submittals/$id': typeof AppSubmittalsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/unauthorized'
    | '/ai'
    | '/apps'
    | '/client-portal'
    | '/documents'
    | '/executive'
    | '/financials'
    | '/hr'
    | '/meetings'
    | '/ncr'
    | '/pm'
    | '/projects'
    | '/reports'
    | '/resources'
    | '/rfi'
    | '/settings'
    | '/submittals'
    | '/users'
    | '/workload'
    | '/invite/$token'
    | '/documents/$id'
    | '/projects/$id'
    | '/rfi/$id'
    | '/submittals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/unauthorized'
    | '/ai'
    | '/apps'
    | '/client-portal'
    | '/documents'
    | '/executive'
    | '/financials'
    | '/hr'
    | '/meetings'
    | '/ncr'
    | '/pm'
    | '/projects'
    | '/reports'
    | '/resources'
    | '/rfi'
    | '/settings'
    | '/submittals'
    | '/users'
    | '/workload'
    | '/invite/$token'
    | '/'
    | '/documents/$id'
    | '/projects/$id'
    | '/rfi/$id'
    | '/submittals/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/unauthorized'
    | '/_app/ai'
    | '/_app/apps'
    | '/_app/client-portal'
    | '/_app/documents'
    | '/_app/executive'
    | '/_app/financials'
    | '/_app/hr'
    | '/_app/meetings'
    | '/_app/ncr'
    | '/_app/pm'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/resources'
    | '/_app/rfi'
    | '/_app/settings'
    | '/_app/submittals'
    | '/_app/users'
    | '/_app/workload'
    | '/invite/$token'
    | '/_app/'
    | '/_app/documents/$id'
    | '/_app/projects/$id'
    | '/_app/rfi/$id'
    | '/_app/submittals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workload': {
      id: '/_app/workload'
      path: '/workload'
      fullPath: '/workload'
      preLoaderRoute: typeof AppWorkloadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submittals': {
      id: '/_app/submittals'
      path: '/submittals'
      fullPath: '/submittals'
      preLoaderRoute: typeof AppSubmittalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rfi': {
      id: '/_app/rfi'
      path: '/rfi'
      fullPath: '/rfi'
      preLoaderRoute: typeof AppRfiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pm': {
      id: '/_app/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof AppPmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ncr': {
      id: '/_app/ncr'
      path: '/ncr'
      fullPath: '/ncr'
      preLoaderRoute: typeof AppNcrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financials': {
      id: '/_app/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AppFinancialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/executive': {
      id: '/_app/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof AppExecutiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client-portal': {
      id: '/_app/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof AppClientPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps': {
      id: '/_app/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submittals/$id': {
      id: '/_app/submittals/$id'
      path: '/$id'
      fullPath: '/submittals/$id'
      preLoaderRoute: typeof AppSubmittalsIdRouteImport
      parentRoute: typeof AppSubmittalsRoute
    }
    '/_app/rfi/$id': {
      id: '/_app/rfi/$id'
      path: '/$id'
      fullPath: '/rfi/$id'
      preLoaderRoute: typeof AppRfiIdRouteImport
      parentRoute: typeof AppRfiRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/documents/$id': {
      id: '/_app/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AppDocumentsIdRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
  }
}

interface AppDocumentsRouteChildren {
  AppDocumentsIdRoute: typeof AppDocumentsIdRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsIdRoute: AppDocumentsIdRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRfiRouteChildren {
  AppRfiIdRoute: typeof AppRfiIdRoute
}

const AppRfiRouteChildren: AppRfiRouteChildren = {
  AppRfiIdRoute: AppRfiIdRoute,
}

const AppRfiRouteWithChildren =
  AppRfiRoute._addFileChildren(AppRfiRouteChildren)

interface AppSubmittalsRouteChildren {
  AppSubmittalsIdRoute: typeof AppSubmittalsIdRoute
}

const AppSubmittalsRouteChildren: AppSubmittalsRouteChildren = {
  AppSubmittalsIdRoute: AppSubmittalsIdRoute,
}

const AppSubmittalsRouteWithChildren = AppSubmittalsRoute._addFileChildren(
  AppSubmittalsRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAppsRoute: typeof AppAppsRoute
  AppClientPortalRoute: typeof AppClientPortalRoute
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
  AppExecutiveRoute: typeof AppExecutiveRoute
  AppFinancialsRoute: typeof AppFinancialsRoute
  AppHrRoute: typeof AppHrRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppNcrRoute: typeof AppNcrRoute
  AppPmRoute: typeof AppPmRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppRfiRoute: typeof AppRfiRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubmittalsRoute: typeof AppSubmittalsRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppWorkloadRoute: typeof AppWorkloadRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAppsRoute: AppAppsRoute,
  AppClientPortalRoute: AppClientPortalRoute,
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
  AppExecutiveRoute: AppExecutiveRoute,
  AppFinancialsRoute: AppFinancialsRoute,
  AppHrRoute: AppHrRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppNcrRoute: AppNcrRoute,
  AppPmRoute: AppPmRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppRfiRoute: AppRfiRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSubmittalsRoute: AppSubmittalsRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppWorkloadRoute: AppWorkloadRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
